name: xpersist-dev
channels:
  - conda-forge
dependencies:
  - boltons
  - cftime
  - codecov
  - dask>=2021.1.0
  - h5netcdf
  - ipython
  - joblib
  - netcdf4>=1.5.5
  - pandas
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-sugar
  - pytest-xdist
  - xarray>=0.16.2
  - zarr>=2.5
  - pip:
      - -e ..
