name: xpersist-dev
channels:
  - conda-forge
dependencies:
  - cftime
  - codecov
  - dask>=2021.1.0
  - h5netcdf
  - ipython
  - netcdf4>=1.5.5
  - pandas
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-sugar
  - pytest-xdist
  - zarr>=2.5
  - pip:
      - git+https://github.com/pydata/xarray.git
      - -e ..
