name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install "dask[complete]" xarray toolz pytest codecov pytest-cov
          python -m pip install .
      - name: Run tests
        run: |
          pytest --junitxml=test-reports/junit.xml --cov=./ --verbose
      - name: Upload coverage
        run: |
          codecov
